name: CI
on: [push]

jobs:
  all:
    name: GitHub Pages, Clippy, Rustfmt, and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2023-03-03
          components: rustfmt, clippy  
      - run: cargo clippy -- -D clippy::pedantic
      - run: cargo fmt --all -- --check
      - run: cargo test
      - run: cargo doc --no-deps --document-private-items --bins --lib
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          keep_files: true
    permissions:
      contents: write           
